Enjoy\UserBundle\Entity\Role:
    type: entity
    table: role
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    manyToOne:
        user:
            targetEntity: User
            inversedBy: roles
            joinColumn:
                name: user_id
                referencedColumnName: id




    fields:
        name:
            type: string
            length: 50
