Enjoy\UserBundle\Entity\Team:
    type: entity
    table: team
    id:
        id:
            type: integer
            generator: { strategy: AUTO }


    fields:
        name:
            type: string
            length: 50







