Enjoy\UserBundle\Entity\User:
    type: entity
    table: user
    repositoryClass: Enjoy\UserBundle\Entity\UserRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    manyToOne:
        team:
            targetEntity: Team
            joinColumn:
                name: team_id
                referencedColumnName: id
    oneToMany:
        roles:
            targetEntity: Role
            mappedBy: user



    fields:
        name:
            type: string
            length: 50
        surname:
            type: string
            length: 50
        email:
            type: string
            length: 50
        password:
            type: string
            length: 100
        salt:
            type: string
            length: 100
#        created_at:
#            type: datetime






