Enjoy\UserBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    manyToOne:
        team:
            targetEntity: Team
            joinColumn:
                name: team_id
                referencedColumnName: id

    fields:
        name:
            type: string
            length: 50
        surname:
            type: string
            length: 50
        email:
            type: string
            length: 50
        password:
            type: string
            length: 100
#        created_at:
#            type: datetime






