jms_security_extra:
    secure_all_services: false
    expressions: true

security:
#     encoders:
#        Docplanner\Userbundle\Entity\User:
#          id: docplanner.user.blowfish_encoder

     encoders:
         Enjoy\UserBundle\Entity\User:
            id: blowfish.encoder



     role_hierarchy:
         ROLE_ADMIN:       ROLE_USER
         ROLE_SUPER_ADMIN: ROLE_ADMIN

     providers:
          administrators:
              entity: { class: EnjoyUserBundle:User }

     firewalls:
         main:
             pattern: ^/
             form_login:
                 provider: administrators
                # csrf_provider: form.csrf_provider
             logout:       true
             anonymous:    true

     access_control:
         - { path: ^/tasks, role: ROLE_ADMIN }
         - { path: ^/add-task, role: ROLE_ADMIN }
         - { path: ^/profile, role: ROLE_ADMIN }