login:
    pattern:   /login
    defaults:  { _controller: EnjoyUserBundle:Security:login }
login_check:
    pattern:   /login_check

logout:
    pattern:  /logout

user_home:
    pattern:  /profile
    defaults: { _controller: EnjoyUserBundle:Profile:show }
    requirements:
            id:  \d+