parameters:
#    enjoy_task.example.class: Enjoy\TaskBundle\Example

services:
#    enjoy_task.example:
#        class: %enjoy_task.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
