Enjoy\TaskBundle\Entity\Task:
    type: entity
    table: task
    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    manyToOne:
        author:
            targetEntity: \Enjoy\UserBundle\Entity\User
            joinColumn:
                name: author_id
                referencedColumnName: id

    fields:
        title:
            type: string
            length: 140
        description:
            type: text
        created_at:
            type: datetime






#	protected $element;
#	protected $group;
#	protected $attachment;
#	protected $author;
#	protected $priority;   http://docs.doctrine-project.org/en/2.0.x/cookbook/mysql-enums.html
